schema_version: 1

context:
  version: "0.96.0"

package:
  name: python-substrait-antlr
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-antlr/substrait_antlr-${{ version }}.tar.gz
  sha256: f645ca0df6ec33b9a423cd58f472280b929a370d9ca4236d473bea986d426b51

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - antlr4-python3-runtime >=4.13,<5

tests:
  - python:
      imports:
        - substrait_antlr.substrait_type.SubstraitTypeParser
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait ANTLR Parser Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  recipe-maintainers:
    - vbarua
    - nielspardon
