schema_version: 1

context:
  version: "0.98.0"

package:
  name: python-substrait-antlr
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-antlr/substrait_antlr-${{ version }}.tar.gz
  sha256: 6a1f33bcd88c425229e42c77079fb0f1f5ad8e0da133e9c1e68048c47104f059

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - antlr4-python3-runtime >=4.13,<5

tests:
  - python:
      imports:
        - substrait_antlr.substrait_type.SubstraitTypeParser
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait ANTLR Parser Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  recipe-maintainers:
    - westonpace
    - epsilonprime
    - jacques-n
    - yongchul
    - benbellick
    - vbarua
    - nielspardon
