schema_version: 1

context:
  version: "0.103.1"

package:
  name: python-substrait-antlr
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-antlr/substrait_antlr-${{ version }}.tar.gz
  sha256: 7be75706e80f4fe3d3ec254f7f105a4fd8eb2ff442ab8e4cafe7803dce1fdbe3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - antlr4-python3-runtime >=4.13,<5

tests:
  - python:
      imports:
        - substrait_antlr.substrait_type.SubstraitTypeParser
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait ANTLR Parser Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  mappings:
    python:
      pypi: substrait-antlr
      import_name: substrait_antlr
  recipe-maintainers:
    - westonpace
    - epsilonprime
    - jacques-n
    - yongchul
    - benbellick
    - vbarua
    - nielspardon
